defaults:
  - _self_
  - agent@_global_: ddpg_mpc
  - mpc@_global_: mpc_agent
  - override hydra/launcher: submitit_local


env: CartPole-BT-v0 #CartPole-BT-dL-v0, CartPole-BT-dH-v0
num_train_states: 1100000
stddev_schedule: 'linear(1.0,0.1,100000)'
action_repeat: 10
# train settings
num_seed_states: 100
# eval
eval_every_states: 2000
num_eval_episodes: 1
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
# misc
seed: 1
device: cuda
save_record: true
use_tb: false
# experiment
experiment: exp
actor_lr: 1e-4
critic_lr: 1e-4
critic_tau: 0.005
alpha_lr: 1e-4
batch_size: 64
num_expl_steps: ${num_seed_states}
params_range: [0.001, 1.]

#MPC config
T: 30
lqr_iter: 5
verbose: -1
eps: 1e-2
exit_unconverged: false

  
hydra:
  run:
    dir: ./experiments/exp_${agent_name}/${now:%Y.%m.%d}_${now:%H%M}_${hydra.job.override_dirname}
  sweep:
    dir: ./experiments/exp_multirun_${agent_name}
    subdir: ${now:%Y.%m.%d}_${now:%H%M}_${hydra.job.override_dirname}
  launcher:
    timeout_min: 18000000
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./experiments/exp_multirun_${agent_name}/${now:%Y.%m.%d}_${now:%H%M}
